services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    init: true # downしてもすぐ終了してくれないので init 経由
    stdin_open: true
    tty: true
    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - type: bind
        source: ./
        target: /app
  
  redis:
    image: redis:alpine
    profiles:
      - local
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - type: bind
        source: ./docker/redis/conf
        target: /usr/local/etc/redis
    ports:
      - target: 6379
        published: ${PUBLISHED_REDIS_PORT:-6379}
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]


volumes:
  redis-data:


